name: Python 3.9, Pytorch 1.11
on:
  workflow_dispatch: # Allow manual triggers
  pull_request:
    branches:
      - main


jobs:
  run-tests:
    uses: ./.github/workflows/run_pytorch_tests.yml
    with:
      python-version: "3.9"
      torch-version: "1.11.*"