name: Python 3.8
on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: 0 0 * * *
  pull_request:
    branches:
      - main


jobs:
  run-testsuite-for-python3.8:
    uses: ./.github/workflows/run_tests_suite_for_python_version.yml
    with:
      python-version: "3.8"