name: Run Keras Tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      tf-version:
        required: true
        type: string

jobs:
  run-tensorflow-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install tensorflow==${{ inputs.tf-version }} sony-custom-layers 
          pip install pytest pytest-mock
          pip check
      - name: Run unittests
        run: |
          # python -m unittest discover tests/keras_tests -v
          pytest tests/keras_tests/feature_networks_tests/test_features_runner.py -k test_mixed_precision_reduced_total_memory -s

#      - name: Run pytest
#        run: |
#          pytest tests_pytest/keras

