name: Run Network Deployment Tests

on:
  workflow_call:
    inputs:
      converter-version:
        required: true
        type: string
      tpc-version:
        required: true
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "torch<2.7" "torchvision<0.22" "onnx<1.18" "onnxruntime<1.22" "onnxruntime-extensions<0.14"
          pip install pytest pytest-mock
          pip list
      - name: Run MCT test
        env:
          TPC_VERSION: ${{inputs.tpc-version}}
        run: |
          pytest tests_pytest/network_deployment_tests/test_run_mct.py
      - name: Set up converter environment
        run: |
          pip uninstall mct-quantizers
          pip install mct-quantizers==${{inputs.converter-mctq-version}}
          pip install imx500-converter[pt]==${{inputs.converter-version}}
      - name: Run Converter test
        run: |
          pytest tests_pytest/network_deployment_tests/test_run_converter.py